!!python/object:huggingface_hub.community.DiscussionWithDetails
author: mahi22muki
conflicting_files: null
created_at: 2023-07-27 11:58:41+00:00
diff: null
endpoint: https://huggingface.co
events:
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/dd2004f6f2ae7d183b618af90b816a32.svg
      fullname: Mukesh Sharma
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: mahi22muki
      type: user
    createdAt: '2023-07-27T12:58:41.000Z'
    data:
      edited: false
      editors:
      - mahi22muki
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.6766091585159302
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/dd2004f6f2ae7d183b618af90b816a32.svg
          fullname: Mukesh Sharma
          isHf: false
          isPro: false
          name: mahi22muki
          type: user
        html: '<p>File "python-3.10.0/lib/python3.10/site-packages/torch/distributed/utils.py",
          line 131, in _sync_params_and_buffers<br>    dist._broadcast_coalesced(<br>RuntimeError:
          Invalid scalar type</p>

          <p>I am trying to run my script  using mpirun</p>

          '
        raw: "File \"python-3.10.0/lib/python3.10/site-packages/torch/distributed/utils.py\"\
          , line 131, in _sync_params_and_buffers\r\n    dist._broadcast_coalesced(\r\
          \nRuntimeError: Invalid scalar type\r\n\r\nI am trying to run my script\
          \  using mpirun\r\n"
        updatedAt: '2023-07-27T12:58:41.420Z'
      numEdits: 0
      reactions: []
    id: 64c26a012152fe05f0505c7a
    type: comment
  author: mahi22muki
  content: "File \"python-3.10.0/lib/python3.10/site-packages/torch/distributed/utils.py\"\
    , line 131, in _sync_params_and_buffers\r\n    dist._broadcast_coalesced(\r\n\
    RuntimeError: Invalid scalar type\r\n\r\nI am trying to run my script  using mpirun\r\
    \n"
  created_at: 2023-07-27 11:58:41+00:00
  edited: false
  hidden: false
  id: 64c26a012152fe05f0505c7a
  type: comment
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/e67a75258b54d2e453c90b65724c87a6.svg
      fullname: Zsolt Egri
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: ezsolt
      type: user
    createdAt: '2023-09-12T19:01:54.000Z'
    data:
      edited: false
      editors:
      - ezsolt
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.9057055711746216
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/e67a75258b54d2e453c90b65724c87a6.svg
          fullname: Zsolt Egri
          isHf: false
          isPro: false
          name: ezsolt
          type: user
        html: '<p>I get the same error when trying to fine tune the model with the
          accelerate API </p>

          '
        raw: 'I get the same error when trying to fine tune the model with the accelerate
          API '
        updatedAt: '2023-09-12T19:01:54.318Z'
      numEdits: 0
      reactions: []
    id: 6500b5a268c6cc778cef69f3
    type: comment
  author: ezsolt
  content: 'I get the same error when trying to fine tune the model with the accelerate
    API '
  created_at: 2023-09-12 18:01:54+00:00
  edited: false
  hidden: false
  id: 6500b5a268c6cc778cef69f3
  type: comment
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/1641757721425-noauth.jpeg?w=200&h=200&f=face
      fullname: Ishan Shanware
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: kernelpanic77
      type: user
    createdAt: '2023-11-25T09:51:43.000Z'
    data:
      edited: false
      editors:
      - kernelpanic77
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.6053223609924316
      isReport: false
      latest:
        author:
          avatarUrl: https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/1641757721425-noauth.jpeg?w=200&h=200&f=face
          fullname: Ishan Shanware
          isHf: false
          isPro: false
          name: kernelpanic77
          type: user
        html: '<p>Any fix for this ? </p>

          '
        raw: 'Any fix for this ? '
        updatedAt: '2023-11-25T09:51:43.084Z'
      numEdits: 0
      reactions: []
    id: 6561c3afb09c0b9eceb9ed7a
    type: comment
  author: kernelpanic77
  content: 'Any fix for this ? '
  created_at: 2023-11-25 09:51:43+00:00
  edited: false
  hidden: false
  id: 6561c3afb09c0b9eceb9ed7a
  type: comment
is_pull_request: false
merge_commit_oid: null
num: 71
repo_id: bigcode/starcoder
repo_type: model
status: open
target_branch: null
title: 'Error :      in _sync_params_and_buffers     dist._broadcast_coalesced( RuntimeError:
  Invalid scalar type'
