!!python/object:huggingface_hub.community.DiscussionWithDetails
author: vasilee
conflicting_files: null
created_at: 2023-06-16 11:46:36+00:00
diff: null
endpoint: https://huggingface.co
events:
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/895f7245c0e03f23e737900bd3e47aa2.svg
      fullname: Vasile Ermicioi
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: vasilee
      type: user
    createdAt: '2023-06-16T12:46:36.000Z'
    data:
      edited: false
      editors:
      - vasilee
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.5564482808113098
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/895f7245c0e03f23e737900bd3e47aa2.svg
          fullname: Vasile Ermicioi
          isHf: false
          isPro: false
          name: vasilee
          type: user
        html: "<p>code that leads to that error</p>\n<pre><code>from ctransformers\
          \ import AutoModelForCausalLM\n\nllm = AutoModelForCausalLM.from_pretrained(\"\
          TheBloke/minotaur-mpt-7B-GGML\",\n                                     \
          \      model_file=\"minotaur-mpt-7b.ggmlv3.q4_1.bin\",\n               \
          \                            model_type=\"mpt\")\nprint(llm('AI is going\
          \ to'))\n</code></pre>\n"
        raw: "code that leads to that error\r\n\r\n```\r\nfrom ctransformers import\
          \ AutoModelForCausalLM\r\n\r\nllm = AutoModelForCausalLM.from_pretrained(\"\
          TheBloke/minotaur-mpt-7B-GGML\",\r\n                                   \
          \        model_file=\"minotaur-mpt-7b.ggmlv3.q4_1.bin\",\r\n           \
          \                                model_type=\"mpt\")\r\nprint(llm('AI is\
          \ going to'))\r\n```"
        updatedAt: '2023-06-16T12:46:36.506Z'
      numEdits: 0
      reactions: []
    id: 648c59ac8c887a7e38f977c2
    type: comment
  author: vasilee
  content: "code that leads to that error\r\n\r\n```\r\nfrom ctransformers import\
    \ AutoModelForCausalLM\r\n\r\nllm = AutoModelForCausalLM.from_pretrained(\"TheBloke/minotaur-mpt-7B-GGML\"\
    ,\r\n                                           model_file=\"minotaur-mpt-7b.ggmlv3.q4_1.bin\"\
    ,\r\n                                           model_type=\"mpt\")\r\nprint(llm('AI\
    \ is going to'))\r\n```"
  created_at: 2023-06-16 11:46:36+00:00
  edited: false
  hidden: false
  id: 648c59ac8c887a7e38f977c2
  type: comment
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/6426d3f3a7723d62b53c259b/tvPikpAzKTKGN5wrpadOJ.jpeg?w=200&h=200&f=face
      fullname: Tom Jobbins
      isHf: false
      isOrgMember: false
      isOwner: true
      isPro: true
      name: TheBloke
      type: user
    createdAt: '2023-06-16T13:07:55.000Z'
    data:
      edited: false
      editors:
      - TheBloke
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.9640921354293823
      isReport: false
      latest:
        author:
          avatarUrl: https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/6426d3f3a7723d62b53c259b/tvPikpAzKTKGN5wrpadOJ.jpeg?w=200&h=200&f=face
          fullname: Tom Jobbins
          isHf: false
          isPro: true
          name: TheBloke
          type: user
        html: '<p>Please double check that the file is properly downloaded. This sounds
          like your download may have aborted part way through.</p>

          '
        raw: Please double check that the file is properly downloaded. This sounds
          like your download may have aborted part way through.
        updatedAt: '2023-06-16T13:07:55.402Z'
      numEdits: 0
      reactions: []
    id: 648c5eab9c935db2b52693e3
    type: comment
  author: TheBloke
  content: Please double check that the file is properly downloaded. This sounds like
    your download may have aborted part way through.
  created_at: 2023-06-16 12:07:55+00:00
  edited: false
  hidden: false
  id: 648c5eab9c935db2b52693e3
  type: comment
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/895f7245c0e03f23e737900bd3e47aa2.svg
      fullname: Vasile Ermicioi
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: vasilee
      type: user
    createdAt: '2023-06-16T14:49:32.000Z'
    data:
      edited: false
      editors:
      - vasilee
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.8911468982696533
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/895f7245c0e03f23e737900bd3e47aa2.svg
          fullname: Vasile Ermicioi
          isHf: false
          isPro: false
          name: vasilee
          type: user
        html: '<p>I downloaded it locally and created a space that is downloading
          on docker the file and it is the same error for q4_0 and q4_1 files. Didn''t
          check the others.<br><a href="https://huggingface.co/spaces/vasilee/wizardcoder-ggml?logs=container">https://huggingface.co/spaces/vasilee/wizardcoder-ggml?logs=container</a></p>

          '
        raw: "I downloaded it locally and created a space that is downloading on docker\
          \ the file and it is the same error for q4_0 and q4_1 files. Didn't check\
          \ the others. \nhttps://huggingface.co/spaces/vasilee/wizardcoder-ggml?logs=container"
        updatedAt: '2023-06-16T14:49:32.512Z'
      numEdits: 0
      reactions: []
    id: 648c767cb970a253c0d4c7e7
    type: comment
  author: vasilee
  content: "I downloaded it locally and created a space that is downloading on docker\
    \ the file and it is the same error for q4_0 and q4_1 files. Didn't check the\
    \ others. \nhttps://huggingface.co/spaces/vasilee/wizardcoder-ggml?logs=container"
  created_at: 2023-06-16 13:49:32+00:00
  edited: false
  hidden: false
  id: 648c767cb970a253c0d4c7e7
  type: comment
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/6426d3f3a7723d62b53c259b/tvPikpAzKTKGN5wrpadOJ.jpeg?w=200&h=200&f=face
      fullname: Tom Jobbins
      isHf: false
      isOrgMember: false
      isOwner: true
      isPro: true
      name: TheBloke
      type: user
    createdAt: '2023-06-16T14:52:05.000Z'
    data:
      edited: false
      editors:
      - TheBloke
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.9632418751716614
      isReport: false
      latest:
        author:
          avatarUrl: https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/6426d3f3a7723d62b53c259b/tvPikpAzKTKGN5wrpadOJ.jpeg?w=200&h=200&f=face
          fullname: Tom Jobbins
          isHf: false
          isPro: true
          name: TheBloke
          type: user
        html: "<p>OK in that case I am not sure</p>\n<p><span data-props=\"{&quot;user&quot;:&quot;marella&quot;}\"\
          \ data-target=\"UserMention\" class=\"SVELTE_PARTIAL_HYDRATER contents\"\
          >\n\n<span class=\"inline-block\"><span class=\"contents\"><a href=\"/marella\"\
          >@<span class=\"underline\">marella</span></a></span>\n\n\t</span></span>\
          \ do you have any idea what might be wrong?</p>\n"
        raw: 'OK in that case I am not sure


          @marella do you have any idea what might be wrong?'
        updatedAt: '2023-06-16T14:52:05.962Z'
      numEdits: 0
      reactions: []
    id: 648c771504d473b756c619d4
    type: comment
  author: TheBloke
  content: 'OK in that case I am not sure


    @marella do you have any idea what might be wrong?'
  created_at: 2023-06-16 13:52:05+00:00
  edited: false
  hidden: false
  id: 648c771504d473b756c619d4
  type: comment
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/93b6433d2741979d473811732948b04d.svg
      fullname: Ravindra Marella
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: marella
      type: user
    createdAt: '2023-06-16T15:49:16.000Z'
    data:
      edited: false
      editors:
      - marella
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.8489875793457031
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/93b6433d2741979d473811732948b04d.svg
          fullname: Ravindra Marella
          isHf: false
          isPro: false
          name: marella
          type: user
        html: '<p>I''m getting the same error with the <a rel="nofollow" href="https://github.com/ggerganov/ggml/blob/master/examples/mpt/main.cpp">example</a>
          in ggml repo.<br>Can you try re-converting and open an issue in ggml repo
          if it still doesn''t work.</p>

          '
        raw: 'I''m getting the same error with the [example](https://github.com/ggerganov/ggml/blob/master/examples/mpt/main.cpp)
          in ggml repo.

          Can you try re-converting and open an issue in ggml repo if it still doesn''t
          work.'
        updatedAt: '2023-06-16T15:49:16.651Z'
      numEdits: 0
      reactions: []
    id: 648c847cc0ddeee6df6c816e
    type: comment
  author: marella
  content: 'I''m getting the same error with the [example](https://github.com/ggerganov/ggml/blob/master/examples/mpt/main.cpp)
    in ggml repo.

    Can you try re-converting and open an issue in ggml repo if it still doesn''t
    work.'
  created_at: 2023-06-16 14:49:16+00:00
  edited: false
  hidden: false
  id: 648c847cc0ddeee6df6c816e
  type: comment
is_pull_request: false
merge_commit_oid: null
num: 1
repo_id: TheBloke/minotaur-mpt-7B-GGML
repo_type: model
status: open
target_branch: null
title: 'mpt_model_load: tensor ''transformer.wte.weight'' has wrong size in model
  file'
