!!python/object:huggingface_hub.community.DiscussionWithDetails
author: andykoko
conflicting_files: null
created_at: 2023-07-19 09:59:27+00:00
diff: null
endpoint: https://huggingface.co
events:
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/321ed23b7cfeeed08c2b408b6a6898c9.svg
      fullname: andykoko
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: andykoko
      type: user
    createdAt: '2023-07-19T10:59:27.000Z'
    data:
      edited: false
      editors:
      - andykoko
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.6535220742225647
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/321ed23b7cfeeed08c2b408b6a6898c9.svg
          fullname: andykoko
          isHf: false
          isPro: false
          name: andykoko
          type: user
        html: "<p>VAEEncoder, VAEDecoder and Unet have been successfully converted,\
          \ but the following error occurred when the step was reached TextEncoder:</p>\n\
          <pre><code>Converting text_encoder\nTraceback (most recent call last):\n\
          \  File \"guernikatools/torch2coreml.py\", line 1679, in &lt;module&gt;\n\
          \  File \"guernikatools/torch2coreml.py\", line 1498, in main\n  File \"\
          guernikatools/torch2coreml.py\", line 299, in convert_text_encoder\nAttributeError:\
          \ 'NoneType' object has no attribute 'model_max_length'\n[2145] Failed to\
          \ execute script 'torch2coreml' due to unhandled exception: 'NoneType' object\
          \ has no attribute 'model_max_length'\n[2145] Traceback:\nTraceback (most\
          \ recent call last):\n  File \"guernikatools/torch2coreml.py\", line 1679,\
          \ in &lt;module&gt;\n  File \"guernikatools/torch2coreml.py\", line 1498,\
          \ in main\n  File \"guernikatools/torch2coreml.py\", line 299, in convert_text_encoder\n\
          AttributeError: 'NoneType' object has no attribute 'model_max_length'\n\
          </code></pre>\n<p>I found that the sd_xl_refiner in Diffusers format only\
          \ contains TextEncoder2 and does not need the smaller TextEncoder. I wonder\
          \ if this is the error caused?<br>So I converted the temporarily generated\
          \ mlpackage to mlmodelc and copy TextEncoder2.mlmodelc from sd_xl_base,\
          \ and then sd_xl_refiner can work properly in Guernika.</p>\n"
        raw: "VAEEncoder, VAEDecoder and Unet have been successfully converted, but\
          \ the following error occurred when the step was reached TextEncoder:\r\n\
          ```\r\nConverting text_encoder\r\nTraceback (most recent call last):\r\n\
          \  File \"guernikatools/torch2coreml.py\", line 1679, in <module>\r\n  File\
          \ \"guernikatools/torch2coreml.py\", line 1498, in main\r\n  File \"guernikatools/torch2coreml.py\"\
          , line 299, in convert_text_encoder\r\nAttributeError: 'NoneType' object\
          \ has no attribute 'model_max_length'\r\n[2145] Failed to execute script\
          \ 'torch2coreml' due to unhandled exception: 'NoneType' object has no attribute\
          \ 'model_max_length'\r\n[2145] Traceback:\r\nTraceback (most recent call\
          \ last):\r\n  File \"guernikatools/torch2coreml.py\", line 1679, in <module>\r\
          \n  File \"guernikatools/torch2coreml.py\", line 1498, in main\r\n  File\
          \ \"guernikatools/torch2coreml.py\", line 299, in convert_text_encoder\r\
          \nAttributeError: 'NoneType' object has no attribute 'model_max_length'\r\
          \n```\r\nI found that the sd_xl_refiner in Diffusers format only contains\
          \ TextEncoder2 and does not need the smaller TextEncoder. I wonder if this\
          \ is the error caused?\r\nSo I converted the temporarily generated mlpackage\
          \ to mlmodelc and copy TextEncoder2.mlmodelc from sd_xl_base, and then sd_xl_refiner\
          \ can work properly in Guernika."
        updatedAt: '2023-07-19T10:59:27.165Z'
      numEdits: 0
      reactions: []
    id: 64b7c20ff72c6cd946dfb7b5
    type: comment
  author: andykoko
  content: "VAEEncoder, VAEDecoder and Unet have been successfully converted, but\
    \ the following error occurred when the step was reached TextEncoder:\r\n```\r\
    \nConverting text_encoder\r\nTraceback (most recent call last):\r\n  File \"guernikatools/torch2coreml.py\"\
    , line 1679, in <module>\r\n  File \"guernikatools/torch2coreml.py\", line 1498,\
    \ in main\r\n  File \"guernikatools/torch2coreml.py\", line 299, in convert_text_encoder\r\
    \nAttributeError: 'NoneType' object has no attribute 'model_max_length'\r\n[2145]\
    \ Failed to execute script 'torch2coreml' due to unhandled exception: 'NoneType'\
    \ object has no attribute 'model_max_length'\r\n[2145] Traceback:\r\nTraceback\
    \ (most recent call last):\r\n  File \"guernikatools/torch2coreml.py\", line 1679,\
    \ in <module>\r\n  File \"guernikatools/torch2coreml.py\", line 1498, in main\r\
    \n  File \"guernikatools/torch2coreml.py\", line 299, in convert_text_encoder\r\
    \nAttributeError: 'NoneType' object has no attribute 'model_max_length'\r\n```\r\
    \nI found that the sd_xl_refiner in Diffusers format only contains TextEncoder2\
    \ and does not need the smaller TextEncoder. I wonder if this is the error caused?\r\
    \nSo I converted the temporarily generated mlpackage to mlmodelc and copy TextEncoder2.mlmodelc\
    \ from sd_xl_base, and then sd_xl_refiner can work properly in Guernika."
  created_at: 2023-07-19 09:59:27+00:00
  edited: false
  hidden: false
  id: 64b7c20ff72c6cd946dfb7b5
  type: comment
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/1672782907557-6313af200b24eab4746e7d34.jpeg?w=200&h=200&f=face
      fullname: Guillermo Cique
      isHf: false
      isOrgMember: true
      isOwner: false
      isPro: false
      name: GuiyeC
      type: user
    createdAt: '2023-07-21T19:46:55.000Z'
    data:
      edited: false
      editors:
      - GuiyeC
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.8410239219665527
      isReport: false
      latest:
        author:
          avatarUrl: https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/1672782907557-6313af200b24eab4746e7d34.jpeg?w=200&h=200&f=face
          fullname: Guillermo Cique
          isHf: false
          isPro: false
          name: GuiyeC
          type: user
        html: "<p><span data-props=\"{&quot;user&quot;:&quot;andykoko&quot;}\" data-target=\"\
          UserMention\" class=\"SVELTE_PARTIAL_HYDRATER contents\">\n\n<span class=\"\
          inline-block\"><span class=\"contents\"><a href=\"/andykoko\">@<span class=\"\
          underline\">andykoko</span></a></span>\n\n\t</span></span> this should be\
          \ fixed in the latest version of the converter, thanks for the report</p>\n"
        raw: '@andykoko this should be fixed in the latest version of the converter,
          thanks for the report'
        updatedAt: '2023-07-21T19:46:55.261Z'
      numEdits: 0
      reactions: []
    id: 64bae0afe38420aaba9219ba
    type: comment
  author: GuiyeC
  content: '@andykoko this should be fixed in the latest version of the converter,
    thanks for the report'
  created_at: 2023-07-21 18:46:55+00:00
  edited: false
  hidden: false
  id: 64bae0afe38420aaba9219ba
  type: comment
is_pull_request: false
merge_commit_oid: null
num: 23
repo_id: Guernika/CoreMLStableDiffusion
repo_type: model
status: open
target_branch: null
title: GuernikaModelConverter  can't convert sd_xl_refiner TextEncoder
