!!python/object:huggingface_hub.community.DiscussionWithDetails
author: whoknowsmeinhf
conflicting_files: null
created_at: 2023-11-24 07:49:52+00:00
diff: null
endpoint: https://huggingface.co
events:
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/217f2e89fd5899e1b68ccfe51202e95a.svg
      fullname: Vinay
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: whoknowsmeinhf
      type: user
    createdAt: '2023-11-24T07:49:52.000Z'
    data:
      edited: false
      editors:
      - whoknowsmeinhf
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.4909743070602417
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/217f2e89fd5899e1b68ccfe51202e95a.svg
          fullname: Vinay
          isHf: false
          isPro: false
          name: whoknowsmeinhf
          type: user
        html: "<p>Added model_type='zephyr' in CTransformers. </p>\n<pre><code>File\
          \ \"llm.py\", line 6, in &lt;module&gt;\n    llm = AutoModelForCausalLM.from_pretrained(\"\
          zephyr-7b-alpha.Q5_K_M.gguf\",model_type=\"zephyr\",seed=0)\n  File \"/usr/local/lib/python3.9/site-packages/ctransformers-0.2.23-py3.9-linux-x86_64.egg/ctransformers/hub.py\"\
          , line 178, in from_pretrained\n    return LLM(\n  File \"/usr/local/lib/python3.9/site-packages/ctransformers-0.2.23-py3.9-linux-x86_64.egg/ctransformers/llm.py\"\
          , line 234, in __init__\n    raise RuntimeError(\n</code></pre>\n"
        raw: "Added model_type='zephyr' in CTransformers. \r\n\r\n```\r\nFile \"llm.py\"\
          , line 6, in <module>\r\n    llm = AutoModelForCausalLM.from_pretrained(\"\
          zephyr-7b-alpha.Q5_K_M.gguf\",model_type=\"zephyr\",seed=0)\r\n  File \"\
          /usr/local/lib/python3.9/site-packages/ctransformers-0.2.23-py3.9-linux-x86_64.egg/ctransformers/hub.py\"\
          , line 178, in from_pretrained\r\n    return LLM(\r\n  File \"/usr/local/lib/python3.9/site-packages/ctransformers-0.2.23-py3.9-linux-x86_64.egg/ctransformers/llm.py\"\
          , line 234, in __init__\r\n    raise RuntimeError(\r\n```"
        updatedAt: '2023-11-24T07:49:52.572Z'
      numEdits: 0
      reactions: []
    id: 656055a0d2cf49994ac25a85
    type: comment
  author: whoknowsmeinhf
  content: "Added model_type='zephyr' in CTransformers. \r\n\r\n```\r\nFile \"llm.py\"\
    , line 6, in <module>\r\n    llm = AutoModelForCausalLM.from_pretrained(\"zephyr-7b-alpha.Q5_K_M.gguf\"\
    ,model_type=\"zephyr\",seed=0)\r\n  File \"/usr/local/lib/python3.9/site-packages/ctransformers-0.2.23-py3.9-linux-x86_64.egg/ctransformers/hub.py\"\
    , line 178, in from_pretrained\r\n    return LLM(\r\n  File \"/usr/local/lib/python3.9/site-packages/ctransformers-0.2.23-py3.9-linux-x86_64.egg/ctransformers/llm.py\"\
    , line 234, in __init__\r\n    raise RuntimeError(\r\n```"
  created_at: 2023-11-24 07:49:52+00:00
  edited: false
  hidden: false
  id: 656055a0d2cf49994ac25a85
  type: comment
is_pull_request: false
merge_commit_oid: null
num: 6
repo_id: TheBloke/zephyr-7B-beta-GGUF
repo_type: model
status: open
target_branch: null
title: Failed to create LLM 'zephyr' from '/models/zephyr-7b-alpha.Q5_K_M.gguf'.
