!!python/object:huggingface_hub.community.DiscussionWithDetails
author: infiniteperplexity
conflicting_files: null
created_at: 2023-07-19 22:13:14+00:00
diff: null
endpoint: https://huggingface.co
events:
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/8bb0658b2da42a3537166164c8b5d5f1.svg
      fullname: Glenn T Wright
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: infiniteperplexity
      type: user
    createdAt: '2023-07-19T23:13:14.000Z'
    data:
      edited: false
      editors:
      - infiniteperplexity
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.9486154913902283
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/8bb0658b2da42a3537166164c8b5d5f1.svg
          fullname: Glenn T Wright
          isHf: false
          isPro: false
          name: infiniteperplexity
          type: user
        html: '<p>This model throws the following error when I attempt to load it.</p>

          '
        raw: This model throws the following error when I attempt to load it.
        updatedAt: '2023-07-19T23:13:14.432Z'
      numEdits: 0
      reactions: []
    id: 64b86e0a8e83b45853a52f8f
    type: comment
  author: infiniteperplexity
  content: This model throws the following error when I attempt to load it.
  created_at: 2023-07-19 22:13:14+00:00
  edited: false
  hidden: false
  id: 64b86e0a8e83b45853a52f8f
  type: comment
is_pull_request: false
merge_commit_oid: null
num: 3
repo_id: microsoft/unilm-base-cased
repo_type: model
status: open
target_branch: null
title: 'ValueError: Unrecognized model in microsoft/unilm-large-cased. Should have
  a `model_type` key in its config.json'
