!!python/object:huggingface_hub.community.DiscussionWithDetails
author: MAVS
conflicting_files: null
created_at: 2022-11-29 11:48:18+00:00
diff: null
endpoint: https://huggingface.co
events:
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/9819e7750e57efd7d7a6c8623fae29eb.svg
      fullname: Maverickccs
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: MAVS
      type: user
    createdAt: '2022-11-29T11:48:18.000Z'
    data:
      edited: false
      editors:
      - MAVS
      hidden: false
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/9819e7750e57efd7d7a6c8623fae29eb.svg
          fullname: Maverickccs
          isHf: false
          isPro: false
          name: MAVS
          type: user
        html: '<p>I am trying to use "git clone" but it''s impossible:</p>

          <p>"Error: Failed to call git rev-parse --git-dir --show-toplevel: "fatal:
          not a git repository (or any of the parent directories): .git\n"<br>Git
          LFS initialized.<br>Cloning into ''stable-diffusion-v1-5''...<br>fatal:
          could not read Username for ''<a rel="nofollow" href="https://huggingface.co''">https://huggingface.co''</a>:
          No such device or address"</p>

          '
        raw: "I am trying to use \"git clone\" but it's impossible:\r\n\r\n\"Error:\
          \ Failed to call git rev-parse --git-dir --show-toplevel: \"fatal: not a\
          \ git repository (or any of the parent directories): .git\\n\"\r\nGit LFS\
          \ initialized.\r\nCloning into 'stable-diffusion-v1-5'...\r\nfatal: could\
          \ not read Username for 'https://huggingface.co': No such device or address\""
        updatedAt: '2022-11-29T11:48:18.154Z'
      numEdits: 0
      reactions: []
    id: 6385f182988cb440e7cdf87d
    type: comment
  author: MAVS
  content: "I am trying to use \"git clone\" but it's impossible:\r\n\r\n\"Error:\
    \ Failed to call git rev-parse --git-dir --show-toplevel: \"fatal: not a git repository\
    \ (or any of the parent directories): .git\\n\"\r\nGit LFS initialized.\r\nCloning\
    \ into 'stable-diffusion-v1-5'...\r\nfatal: could not read Username for 'https://huggingface.co':\
    \ No such device or address\""
  created_at: 2022-11-29 11:48:18+00:00
  edited: false
  hidden: false
  id: 6385f182988cb440e7cdf87d
  type: comment
is_pull_request: false
merge_commit_oid: null
num: 30
repo_id: runwayml/stable-diffusion-v1-5
repo_type: model
status: open
target_branch: null
title: I can't use git clone in colab
